version: 2
jobs:
    build:
     docker:
        - image: circleci/python:3.8
          environment:

     steps:
        - checkout
        - run:
            name: deps
            command: |
                #apt install python-pip
                # pip install --user --upgrade -r requirements.txt
                python3 -m pip install nosetests

        - run:
            name: build
            command: |
              python3 -m pip install -e .

        - run:
            name: build
            command: |
              nosetests duckietown_tokens_tests

        - run:
            name: dts help
            command: |
               export PATH=/home/circleci/.local/bin:$PATH
               dts help

        - run:
            name: dts version
            command: |
               export PATH=/home/circleci/.local/bin:$PATH
               dts version
#
#        - run:
#            name: dts aido token
#            command: |
#               export PATH=/home/circleci/.local/bin:$PATH
#               dts aido18 token dt1-XXzMstGtdJhJeXv-43dzqWFnWd8KBa1yev1g3UKnzVxZkkTbfQj2vduBXhfPjK6FSSCHQZPr986b8tXASH || true
